In [339]:
import pandas as pd
import plotly.express as px

In [340]:
color_dict = {
    'PWRCRUD001': 'gray',
    'PWRCRUD002': 'dimgray',
    'PWRCRUD003': 'darkgray',
    'PWRCRUD004': 'silver',
    'PWRCRUD005': 'lightgray',
    'PWRCRUD006': 'gainsboro',
    'PWRCRUD007': 'whitesmoke',
    'PWRCRUD008': 'black',
    'PWRHFO01': '#8B0000',
    'PWRNG01': 'orange',
    'PWRNG02': 'darkorange',
    'PWRGHFO2': 'gray',
    'PWRBIO': '#9ACD32',
    'PWRWND001': 'deepskyblue',#4169E1
    'PWRWND002': 'deepskyblue',
    'PWRPV01': '#FFD700',
    'PWRPV02': 'gold',
    'PWRCSP': 'gray',
    'PWRFO': '#FF6961',
    'PWRDSL': 'brown',
    'PWRHYD01': 'gray',
    'PWRHYD02': 'gray'
}

In [341]:
RateOfProductionByTechnology = pd.read_csv('../../results/v_RateOfProductionByTechnology.csv')
RateOfProductionByTechnology['TIMESLICE'] = RateOfProductionByTechnology['TIMESLICE'].astype(str)



RateOfProductionByTechnology= RateOfProductionByTechnology[RateOfProductionByTechnology['TECHNOLOGY'].str.contains('PWR')]
RateOfProductionByTechnology= RateOfProductionByTechnology[round(RateOfProductionByTechnology['value'],4) != 0]
RateOfProductionByTechnology = RateOfProductionByTechnology[~RateOfProductionByTechnology['TECHNOLOGY'].str.contains('PWRDIST|PWRTRANS')]
# Create a stacked bar chart using Plotly with custom colors
fig = px.bar(RateOfProductionByTechnology, x='TIMESLICE', y='value', color='TECHNOLOGY', animation_frame='YEAR',
             labels={'value': 'Energy (PJ)'}, 
             width=700,
             height=600,
             category_orders={'TIMESLICE': RateOfProductionByTechnology['TIMESLICE'], 'YEAR': RateOfProductionByTechnology['YEAR']},
             color_discrete_map=color_dict
             )

fig.update_layout(updatemenus=[dict(type='buttons', showactive=False, buttons=[dict(args=[None, dict(frame=dict(duration=200, redraw=True), fromcurrent=True)])])])

# Show the interactive plot
fig.show()

In [342]:
TotalDiscountedCost = pd.read_csv('../../results/v_TotalDiscountedCost.csv')

In [447]:
TotalCapacityAnnual = pd.read_csv('../../results/v_TotalCapacityAnnual.csv')
TotalCapacityAnnual = TotalCapacityAnnual[TotalCapacityAnnual['value'] != 0]
TotalCapacityAnnual= TotalCapacityAnnual[TotalCapacityAnnual['TECHNOLOGY'].str.contains('PWR')].sort_values(by='TECHNOLOGY')
TotalCapacityAnnual = TotalCapacityAnnual[~TotalCapacityAnnual['TECHNOLOGY'].str.contains('PWRDIST|PWRTRANS')]
fig = px.bar(TotalCapacityAnnual, 
             x='YEAR', y='value', 
             color= 'TECHNOLOGY',
             color_discrete_map = color_dict,
             opacity=0.9
             )
fig.update_layout(hovermode= 'x unified',
                  width= 600,
                  height= 600,
                  barcornerradius=10,
                  
               #color_discrete_map=color_map
               )
fig.show()#  ~ esto filtra las que no quieres

In [404]:
TotalCapacityAnnual = pd.read_csv('../../results/v_TotalCapacityAnnual.csv')

In [490]:
ProductionByTechnologyAnnual = pd.read_csv('../../results/v_ProductionByTechnologyAnnual.csv')
ProductionByTechnologyAnnual= ProductionByTechnologyAnnual[ProductionByTechnologyAnnual['TECHNOLOGY'].str.contains('PWR')].sort_values(by='TECHNOLOGY')
ProductionByTechnologyAnnual = ProductionByTechnologyAnnual[~ProductionByTechnologyAnnual['TECHNOLOGY'].str.contains('PWRDIST|PWRTRANS')]
ProductionByTechnologyAnnual = ProductionByTechnologyAnnual[round(ProductionByTechnologyAnnual['value'],4) != 0]
fig = px.bar(ProductionByTechnologyAnnual, x="YEAR", y = "value", color="TECHNOLOGY",
             color_discrete_map = color_dict,
             opacity = 0.7,
             )

fig.update_layout(hovermode='x unified', 
                  autosize=False,
                  width= 1000,
                  height= 600, 
                  yaxis_title="ProductionByTechnologyAnnual PJ",
                  plot_bgcolor='white',
                #   paper_bgcolor='lightgrey',
                 xaxis=dict(
        tickfont=dict(size=14),  # Tamaño de la fuente de las etiquetas del eje x
        titlefont=dict(size=14)
                ),
                  yaxis=dict(
        showgrid=False,
        tickfont=dict(size=14),      
        gridwidth=0.5,        #
        gridcolor='lightgrey',
        
        )

)
fig.show()

# fig.update_layout(updatemenus=[dict(type='buttons', showactive=False, buttons=[dict(args=[None, dict(frame=dict(duration=500, redraw=True), fromcurrent=True)])])])

In [426]:
fig = px.pie(ProductionByTechnologyAnnual[ProductionByTechnologyAnnual['YEAR']==2030],
             names = 'TECHNOLOGY', 
             values = 'value',
             hole = 0.5,
             color = 'TECHNOLOGY',
color_discrete_map = color_dict,
opacity=0.7
             
             )
fig.update_layout(hovermode= 'x unified',
                  title = 'Energy production base scenario by technology ',
                  width= 600,
                  height= 600,
                  font=dict(
                                  size=16,
                                 color='black')


               )
fig.show()

In [487]:
fig1 = px.pie(ProductionByTechnologyAnnual[ProductionByTechnologyAnnual['YEAR']==2030], names='TECHNOLOGY', values='value', hole=0.5, title='Gráfico de Dona 1',color = 'TECHNOLOGY',color_discrete_map = color_dict,
opacity=0.7)
fig2 = px.pie(ProductionByTechnologyAnnual[ProductionByTechnologyAnnual['YEAR']==2050], names='TECHNOLOGY', values='value', hole=0.5, title='Gráfico de Dona 2',color = 'TECHNOLOGY',color_discrete_map = color_dict,
opacity=0.7)
from plotly.subplots import make_subplots

fig = make_subplots(
    rows=1, cols=2, 
    specs=[[{'type': 'domain'}, {'type': 'domain'}]],
    subplot_titles=('2030', '2050')
)


for trace in fig1.data:
    fig.add_trace(trace, row=1, col=1)

for trace in fig2.data:
    fig.add_trace(trace, row=1, col=2)

fig.update_layout(height=600, width=800,title={'text': 'Energy Production by technology', 'x': 0.5} , font=dict( size=16,color='black'))

fig.show()

In [401]:
NewCapacity = pd.read_csv('../../results/v_NewCapacity.csv')
NewCapacity = NewCapacity[NewCapacity['value'] != 0]
NewCapacity= NewCapacity[NewCapacity['TECHNOLOGY'].str.contains('PWR')]
NewCapacity = NewCapacity[~NewCapacity['TECHNOLOGY'].str.contains('PWRDIST|PWRTRANS')] #  ~ esto filtra las que no quieres

In [402]:
fig = px.pie(NewCapacity,
             names = 'TECHNOLOGY', 
             values = 'value',
             hole = 0.5,
             color = 'TECHNOLOGY',
color_discrete_map = color_dict,
opacity=0.7
             
             )
fig.update_layout(hovermode= 'x unified',
                  width= 600,
                  height= 600,
                  font=dict(
                                  size=20,
                                 color='black')

               #color_discrete_map=color_map
               )
fig.show()

In [475]:
NewCapacity[NewCapacity['TECHNOLOGY'].isin(['PWRFO'])]
[~NewCapacity['TECHNOLOGY'].str.contains('PWRDIST|PWRTRANS')]

     REGION TECHNOLOGY  YEAR     value
1078   Cuba      PWRFO  2041  0.175206

In [496]:
TotalCapacityAnnual = TotalCapacityAnnual.sort_values(by=['TECHNOLOGY', 'YEAR'])
TotalCapacity203050 = TotalCapacityAnnual[TotalCapacityAnnual['YEAR'].isin([2020,2030,2040,2050])]
TotalCapacity203050 = TotalCapacity203050[TotalCapacity203050['TECHNOLOGY'].isin(NewCapacity.TECHNOLOGY.unique())]
TotalCapacity203050 = TotalCapacity203050[~TotalCapacity203050['TECHNOLOGY'].isin(['PWRFO'])]
fig = px.scatter(TotalCapacity203050,  #df[df['YEAR'].isin(filtered_years)
            y = 'value', 
            x = 'YEAR',
            #  values = 'value',
            #  hole = 0.5,
             color = 'TECHNOLOGY',
color_discrete_map = color_dict,
# opacity=0.7
             
             )
fig.update_layout(hovermode= 'x unified',
                width= 800,
                height= 600,
                yaxis_title="Capacity GW",
                plot_bgcolor='white',
                font=dict(
                                size=20,
                                color='black'),
                yaxis=dict(
                                showgrid=True,
                                tickfont=dict(size=16),      
                                gridwidth=0.5,        #
                                gridcolor='lightgrey',
        
                                ),
                # title_text='New installed capacity over the years' 
                title={'text': 'Accumulated Installed Capacity Over the Years', 'x': 0.5}              

               #color_discrete_map=color_map
               )
fig.update_traces(mode='lines+markers', line=dict(width=4), marker=dict(size=10))
fig.update_xaxes(tickvals=[2020, 2030, 2040, 2050])
fig.show()

In [417]:
TotalCapacityAnnual[TotalCapacityAnnual['TECHNOLOGY'].str.contains('PWRPV01')]
Annual2030 = TotalCapacityAnnual[TotalCapacityAnnual['TECHNOLOGY'].str.contains('PWR') & (TotalCapacityAnnual['YEAR']==2030) & (TotalCapacityAnnual['value']!=0)]
Annual2030 = Annual2030[~Annual2030['TECHNOLOGY'].str.contains('PWRDIST|PWRTRANS')]

In [418]:
fig = px.pie(Annual2030,
             names = 'TECHNOLOGY', 
             values = 'value',
             hole = 0.5,
             color = 'TECHNOLOGY',
color_discrete_map = color_dict,
opacity=0.7
             
             )
fig.update_layout(hovermode= 'x unified',
                  width= 600,
                  height= 600,
                  font=dict(
                                  size=20,
                                 color='black')

               #color_discrete_map=color_map
               )
fig.show()

In [349]:

fig = px.bar(NewCapacity, 
             x='YEAR', y='value', 
             color= 'TECHNOLOGY',
             color_discrete_map = color_dict,
             opacity=0.6
             )
fig.update_layout(hovermode= 'x unified',
                  width= 600,
                  height= 600,
                  barcornerradius=10,
                  
               #color_discrete_map=color_map
               )
fig.show()

In [350]:
Capital = pd.read_csv('../../results/v_CapitalInvestment.csv')
CapitalInvestmentStorage = pd.read_csv('../../results/v_CapitalInvestmentStorage.csv')
CapitalInvestmentStorage

   REGION STORAGE  YEAR  value
0    Cuba     DAM  2019    0.0
1    Cuba     DAM  2020    0.0
2    Cuba     DAM  2021    0.0
3    Cuba     DAM  2022    0.0
4    Cuba     DAM  2023    0.0
..    ...     ...   ...    ...
91   Cuba  Batt02  2046    0.0
92   Cuba  Batt02  2047    0.0
93   Cuba  Batt02  2048    0.0
94   Cuba  Batt02  2049    0.0
95   Cuba  Batt02  2050    0.0

[96 rows x 4 columns]

In [351]:
fig = px.area(Capital, x='YEAR', y='value', color= 'TECHNOLOGY',)
fig.update_layout(hovermode= 'x unified',                   autosize=False,
                  width= 1200,
                  height= 800)

fig.show()

In [352]:
NetChargeWithinDay = pd.read_csv('../../results/v_NetChargeWithinDay.csv')

In [353]:
fig = px.bar(NetChargeWithinDay, x='DAILYTIMEBRACKET', y='value', color= 'STORAGE',)
fig.update_layout(hovermode= 'x unified',                   autosize=False,
                  width= 1200,
                  height= 800)

fig.show()

In [354]:
RateOfStorageDischarge = pd.read_csv('../../results/v_RateOfStorageDischarge.csv')
fig = px.bar(RateOfStorageDischarge, x='DAILYTIMEBRACKET', y='value', color= 'STORAGE',)
fig.update_layout(hovermode= 'x unified',                   autosize=False,
                  width= 1200,
                  height= 800)

fig.show()

In [355]:
RateOfStorageDischarge.drop('REGION', axis =1)

     STORAGE  SEASON  DAYTYPE  DAILYTIMEBRACKET  YEAR  value
0        DAM       1        1                 1  2019    0.0
1        DAM       1        1                 1  2020    0.0
2        DAM       1        1                 1  2021    0.0
3        DAM       1        1                 1  2022    0.0
4        DAM       1        1                 1  2023    0.0
...      ...     ...      ...               ...   ...    ...
6139  Batt02       4        2                 8  2046    0.0
6140  Batt02       4        2                 8  2047    0.0
6141  Batt02       4        2                 8  2048    0.0
6142  Batt02       4        2                 8  2049    0.0
6143  Batt02       4        2                 8  2050    0.0

[6144 rows x 6 columns]

In [356]:
NewStorageCapacity = pd.read_csv('../../results/v_NewStorageCapacity.csv')
NewStorageCapacity = NewStorageCapacity[NewStorageCapacity['value'] != 0]
fig = px.bar(NewStorageCapacity, x='YEAR', y='value', color= 'STORAGE',)
fig.update_layout(hovermode= 'x unified')
fig.show()